### ISSUE TITLE
iOS crash at startup

### ISSUE THREAD

**Issue by gaetandezeiraud** [kniEngine/kni#1596]
When I tried to run in Debug or Release mode the startup iOS project It crash at startup.
I am using KNI 3.12.9001 on macOS 14.5 (23F79). MacBook M2 (ARM64).

But I use .NET x64 like recommanded by Monogame for compiling.

Here the output on the default project template without modification:
```
2024-05-22 17:33:31.597487+0200 Game1iOS[68070:1129624] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68070
2024-05-22 17:33:31.606955+0200 Game1iOS[68070:1129624] SecTaskCopyDebugDescription: Game1iOS[68070]/0#-1 LF=0
2024-05-22 17:33:31.791556+0200 Game1iOS[68070:1129624] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68070
2024-05-22 17:33:31.791714+0200 Game1iOS[68070:1129624] SecTaskCopyDebugDescription: Game1iOS[68070]/0#-1 LF=0
2024-05-22 17:33:31.791889+0200 Game1iOS[68070:1129624] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=68070
2024-05-22 17:33:31.791975+0200 Game1iOS[68070:1129624] SecTaskCopyDebugDescription: Game1iOS[68070]/0#-1 LF=0
2024-05-22 17:33:32.039409+0200 Game1iOS[68070:1129624] GameFactory not found.
2024-05-22 17:33:32.041028+0200 Game1iOS[68070:1129624] Initialize input with 'GameFactory.RegisterGameFactory(new ConcreteGameFactory());'.
2024-05-22 17:33:32.041605+0200 Game1iOS[68070:1129624] Registering ConcreteGameFactoryStrategy through reflection.
Loaded assembly: /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/MonoGame.Framework.dll [External]
2024-05-22 17:33:58.198277+0200 Game1iOS[68070:1129624] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
   at Microsoft.Xna.Framework.Game.get_Services()
   at Microsoft.Xna.Platform.ConcreteGame..ctor(Game )
   at Microsoft.Xna.Platform.ConcreteGameFactory.CreateGameStrategy(Game )
   at Microsoft.Xna.Framework.Game..ctor()
   at Game1iOS.Game1iOSGame..ctor() in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Game1iOSGame.cs:line 20
   at Game1iOS.Program.RunGame() in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 14
   at Game1iOS.Program.FinishedLaunching(UIApplication ) in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 28
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr ) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] , String , String ) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 84
   at Game1iOS.Program.Main(String[] ) in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 23

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10ad81af5 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10ad204fe - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10b078b58 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x10ad81430 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x10ce18fdd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x10d050d1c - /Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10a6b90e7 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libxamarin-dotnet-debug.dylib : xamarin_unhandled_exception_handler
	0x10ae1f104 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x10acd5b92 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10a6ccbea - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x100d3bd74 - /Users/gaetandezeiraud/Library/Developer/CoreSimulator/Devices/6B3F2C7E-1C4F-4839-83A7-F4AA205542F4/data/Containers/Bundle/Application/3B49EDE0-98B0-4305-9951-371E272B7B75/Game1iOS.app/Game1iOS : main
	0x1096023e0 - Unknown
	0x200f1a366 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10d7b614a):0x10d7b613a  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x10d7b614a  73 08 48 89 c7 e9 cc 99 ff ff c3 90 90 90 b8 53  s.H............S
0x10d7b615a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 b4 99  ...I....s.H.....
0x10d7b616a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

I have the same problem on a more advanced project. Who run correctly on Android and Windows.

**Comment by gaetandezeiraud** [comment]
Hi and thank you for the anwser. I tried to add `RegisterGameFactory` before the `new Game()`. But it is not success. Same error. Here the code:

```csharp
internal static void RunGame()
        {
            GameFactory.RegisterGameFactory(new ConcreteGameFactory());
            game = new Game1iOSGame();
            game.Run();
        }
```

And the error:
```
2024-05-25 10:05:20.714656+0200 Game1iOS[17249:1614841] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
   at Microsoft.Xna.Framework.Game.get_Services()
   at Microsoft.Xna.Platform.ConcreteGame..ctor(Game )
   at Microsoft.Xna.Platform.ConcreteGameFactory.CreateGameStrategy(Game )
   at Microsoft.Xna.Framework.Game..ctor()
   at Game1iOS.Game1iOSGame..ctor() in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Game1iOSGame.cs:line 20
   at Game1iOS.Program.RunGame() in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 16
   at Game1iOS.Program.FinishedLaunching(UIApplication ) in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 30
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr ) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] , String , String ) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 84
   at Game1iOS.Program.Main(String[] ) in /Users/gaetandezeiraud/Desktop/Game1iOS/Game1iOS/Program.cs:line 25
```
