### ISSUE TITLE
Kni Pipeline tool crashes when using Build Action:Copy and Platform: BlazorGL

### ISSUE THREAD

**Issue by NebulaSleuth** [kniEngine/kni#796]
Kni Pipeline tool crashes when using Build Action:Copy and Platform: BlazorGL
I had to include 2 files with build Action COPY before it crashed.  A single one did not seem to do it.

Application: PipelineEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at System.Diagnostics.Process.OutputReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by nkast** [comment]
I'm suspecting that one or both of the files failed to copy, which triggers a race condition in CopyItems #894.
Under ideal conditions, CopyItems() writes a single line to the console. ```Console.WriteLine(item.SourceFile);``` 
that wouldn't cause any issues.

Additionally the output parser in the editor failed to correctly parse the output, and crash. Hopefully #890 will let you see why it failed.

**Comment by nkast** [comment]
this has been fixed in v3.10.
